# docker-compose.yml (dev)
services:
  mongo:
    image: mongo:6
    container_name: multi-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: multi-api
    env_file:
      - backend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: multi-store
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - WATCHPACK_POLLING=true
      - NODE_OPTIONS=--max_old_space_size=2048
      - DOCKER=1
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: sh -c "npm run dev -- -H 0.0.0.0"
    restart: unless-stopped

  frontend_admin:
    build:
      context: ./frontend-admin
      dockerfile: Dockerfile.dev
    container_name: multi-admin
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
      - WATCHPACK_POLLING=true
      - NODE_OPTIONS=--max_old_space_size=2048
      - DOCKER=1
    volumes:
      - ./frontend-admin:/app
      - /app/node_modules
    ports:
      - "3001:3001"
    depends_on:
      - backend
    command: sh -c "npm run dev -- -H 0.0.0.0"
    restart: unless-stopped

volumes:
  mongo-data:
