version: "3.9"
services:
  edge:
    build:
      context: ./edge
      dockerfile: Dockerfile
    depends_on: [backend, frontend, frontend_admin]
    ports: ["8080:80"]                # single public entry
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: production
      PORT: "8000"
      # pull these from your shell or an .env file next to this compose
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      SMTP_SERVICE: ${SMTP_SERVICE}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_EMAIL: ${SMTP_EMAIL}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      CLOUD_NAME: ${CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    expose: ["8000"]
    env_file:
      - .env.prod   
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        # internal service URL for SSR/server
        NEXT_PUBLIC_API_URL: http://backend:8000
    environment:
      NODE_ENV: production
      PORT: "3000"
    expose: ["3000"]
    restart: unless-stopped

  frontend_admin:
    build:
      context: ./frontend-admin
      dockerfile: Dockerfile.prod
      args:
        NEXT_PUBLIC_API_URL: http://backend:8000
    environment:
      NODE_ENV: production
      PORT: "3001"
    expose: ["3001"]
    restart: unless-stopped
